"""empty message

Revision ID: d7da19cd0641
Revises: cc74cee2cc13
Create Date: 2021-12-01 21:29:27.472214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7da19cd0641'
down_revision = 'cc74cee2cc13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bookings_priest_id_fkey', 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'priest_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('priest_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('bookings_priest_id_fkey', 'bookings', 'users', ['priest_id'], ['id'])
    # ### end Alembic commands ###
