"""empty message

Revision ID: 57972fa41da9
Revises: d7da19cd0641
Create Date: 2021-12-01 21:33:43.025014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57972fa41da9'
down_revision = 'd7da19cd0641'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('priests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('priest_id', sa.Integer(), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['priest_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('priests')
    # ### end Alembic commands ###
