"""empty message

Revision ID: 4688c36afa0d
Revises: d20143f655b1
Create Date: 2021-12-01 20:12:08.839645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4688c36afa0d'
down_revision = 'd20143f655b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ceremony_type', sa.String(length=100), nullable=False),
    sa.Column('firstName', sa.String(length=100), nullable=False),
    sa.Column('lastName', sa.String(length=100), nullable=False),
    sa.Column('home_church', sa.String(length=255), nullable=False),
    sa.Column('bookingDay', sa.Date(), nullable=False),
    sa.Column('bookingTime', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('priest_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['priest_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    # ### end Alembic commands ###
