"""empty message

Revision ID: cc74cee2cc13
Revises: 4688c36afa0d
Create Date: 2021-12-01 20:43:10.704176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc74cee2cc13'
down_revision = '4688c36afa0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prayers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('prayer_request_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prayer_request_id'], ['prayer_requests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prayers')
    # ### end Alembic commands ###
